version: '3.8'

services:
  frontend:
    image: lmessia93/pizzatech-front
    container_name: pizzatech-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  backend:
    image: lmessia93/pizzatech-back
    container_name: pizzatech-backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://localhost:4000/api
      - FRONTEND_URL=http://localhost:5173
    command: ["npm", "run", "dev"]

  rocket-ecommerce:
    image: lmessia93/rocket-ecommerce
    container_name: rocket-ecommerce
    ports:
      - "5085:5005"
    environment:
      - API_URL=http://localhost:4000/api
      - FRONTEND_URL=http://localhost:5173

  task-api:
    image: lmessia93/task-api
    container_name: task-api
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:4000
