version: '3.8'
services:
  frontend:
    container_name: pizzatech-frontend-dev
    image: lmessia93/pizzatech-front
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5085/api
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  backend:
    container_name: pizzatech-backend-dev
    image: lmessia93/pizzatech-back
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - API_URL=http://localhost:5085/task-api
      - FRONTEND_URL=http://localhost:5085
    command: ["npm", "run", "dev"]

  rocket-ecommerce:
    container_name: rocket-ecommerce
    image: lmessia93/rocket-ecommerce
    ports:
      - "5005:5005"
    environment:
      - API_URL=http://localhost:5085/api
      - FRONTEND_URL=http://localhost:5085

  task-api:
    container_name: task-api
    image: lmessia93/task-api
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - BASE_URL=http://localhost:5085/api

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "5085:5085"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - rocket-ecommerce
      - task-api
  

    
